import { PERMISSION_REGISTRY, type PermissionKey } from "@/domain/authorization/permission-registry";
import type { MessageKey } from "@/domain/i18n/messages";

/** Catalog key for each module group; `core` holds the project-level permissions. */
export const MODULE_LABEL_KEY: Record<string, MessageKey> = {
  core: "permission.module.core",
  issue_tracking: "permission.module.issue_tracking",
  time_tracking: "permission.module.time_tracking",
  wiki: "permission.module.wiki",
  boards: "permission.module.boards",
  news: "permission.module.news",
  documents: "permission.module.documents",
  files: "permission.module.files",
  repository: "permission.module.repository",
  calendar: "permission.module.calendar",
  gantt: "permission.module.gantt",
};

/** Catalog key for each permission, so the admin screens show it in the viewer's locale. */
export const PERMISSION_LABEL_KEY: Record<PermissionKey, MessageKey> = {
  view_project: "permission.view_project",
  search_project: "permission.search_project",
  add_project: "permission.add_project",
  edit_project: "permission.edit_project",
  close_project: "permission.close_project",
  delete_project: "permission.delete_project",
  select_project_publicity: "permission.select_project_publicity",
  select_project_modules: "permission.select_project_modules",
  view_members: "permission.view_members",
  manage_members: "permission.manage_members",
  manage_versions: "permission.manage_versions",
  add_subprojects: "permission.add_subprojects",
  use_webhooks: "permission.use_webhooks",
  save_queries: "permission.save_queries",
  manage_public_queries: "permission.manage_public_queries",
  view_issues: "permission.view_issues",
  add_issues: "permission.add_issues",
  edit_issues: "permission.edit_issues",
  edit_own_issues: "permission.edit_own_issues",
  add_issue_notes: "permission.add_issue_notes",
  edit_issue_notes: "permission.edit_issue_notes",
  edit_own_issue_notes: "permission.edit_own_issue_notes",
  set_notes_private: "permission.set_notes_private",
  view_private_notes: "permission.view_private_notes",
  delete_issues: "permission.delete_issues",
  copy_issues: "permission.copy_issues",
  set_issues_private: "permission.set_issues_private",
  set_own_issues_private: "permission.set_own_issues_private",
  manage_subtasks: "permission.manage_subtasks",
  manage_issue_relations: "permission.manage_issue_relations",
  manage_issue_categories: "permission.manage_issue_categories",
  view_issue_watchers: "permission.view_issue_watchers",
  add_issue_watchers: "permission.add_issue_watchers",
  delete_issue_watchers: "permission.delete_issue_watchers",
  view_time_entries: "permission.view_time_entries",
  log_time: "permission.log_time",
  edit_time_entries: "permission.edit_time_entries",
  edit_own_time_entries: "permission.edit_own_time_entries",
  manage_project_activities: "permission.manage_project_activities",
  log_time_for_other_users: "permission.log_time_for_other_users",
  import_time_entries: "permission.import_time_entries",
  view_wiki_pages: "permission.view_wiki_pages",
  view_wiki_edits: "permission.view_wiki_edits",
  edit_wiki_pages: "permission.edit_wiki_pages",
  rename_wiki_pages: "permission.rename_wiki_pages",
  delete_wiki_pages: "permission.delete_wiki_pages",
  delete_wiki_pages_attachments: "permission.delete_wiki_pages_attachments",
  protect_wiki_pages: "permission.protect_wiki_pages",
  view_wiki_page_watchers: "permission.view_wiki_page_watchers",
  add_wiki_page_watchers: "permission.add_wiki_page_watchers",
  delete_wiki_page_watchers: "permission.delete_wiki_page_watchers",
  manage_wiki: "permission.manage_wiki",
  export_wiki_pages: "permission.export_wiki_pages",
  manage_boards: "permission.manage_boards",
  view_messages: "permission.view_messages",
  add_messages: "permission.add_messages",
  edit_messages: "permission.edit_messages",
  edit_own_messages: "permission.edit_own_messages",
  delete_messages: "permission.delete_messages",
  delete_own_messages: "permission.delete_own_messages",
  view_message_watchers: "permission.view_message_watchers",
  add_message_watchers: "permission.add_message_watchers",
  delete_message_watchers: "permission.delete_message_watchers",
  view_news: "permission.view_news",
  manage_news: "permission.manage_news",
  comment_news: "permission.comment_news",
  view_documents: "permission.view_documents",
  add_documents: "permission.add_documents",
  edit_documents: "permission.edit_documents",
  delete_documents: "permission.delete_documents",
  view_files: "permission.view_files",
  manage_files: "permission.manage_files",
  browse_repository: "permission.browse_repository",
  view_changesets: "permission.view_changesets",
  commit_access: "permission.commit_access",
  import_issues: "permission.import_issues",
  manage_related_issues: "permission.manage_related_issues",
  manage_repository: "permission.manage_repository",
  view_calendar: "permission.view_calendar",
  view_gantt: "permission.view_gantt",
};

export const PERMISSIONS_BY_MODULE = Object.entries(PERMISSION_REGISTRY).reduce<Record<string, PermissionKey[]>>(
  (acc, [key, def]) => {
    const moduleKey = def.module ?? "core";
    acc[moduleKey] = acc[moduleKey] ?? [];
    acc[moduleKey].push(key as PermissionKey);
    return acc;
  },
  {},
);
